### ISSUE TITLE
Niimbot B21

### ISSUE THREAD

**Issue by kris0725pl** [CalciumSelenide/BluetoothAccessories#1]
Hi...i have two Niimbot devices.

D11 and B21.

I need to be a tester your appps...ok?

**Comment by CalciumSelenide** [comment]
@kris0725pl
Hello! If you want a driver for a Niimbot D11, I would consult [kjy00302/niimprint's client](https://github.com/kjy00302/niimprint). As I understand it, both kjy00302 and I have the Niimbot B21 on our radar, but we are both working on them separately and don't have time at the present moment to get them ironed out.

Disclaimer: I am not working with kjy00302 actively - I have looked at their driver though and it looks great and they have plans in the works for it moving forward. 

I will be working on this in the coming months. I do not have a dedicated timeline that this will be finished in, however, due to the fact that I am overextended across many projects.
